maven_layout()

target(name='zipkin-sampler',
  dependencies=[
    'zipkin/oss/zipkin-sampler/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'zipkin/oss/zipkin-sampler/src/test/scala'
  ]
)

