maven_layout()

jar_library(name='zipkin-sampler',
  dependencies=[
    'zipkin/oss/zipkin-sampler/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'zipkin/oss/zipkin-sampler/src/test/scala'
  ]
)

