maven_layout()

jar_library(name='zipkin-sampler',
  dependencies=[
    pants('oss/zipkin-sampler/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-sampler/src/test/scala')
  ]
)

