#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'zipkin_types'

  module Zipkin
    CLIENT_SEND = %q"cs"

    CLIENT_RECV = %q"cr"

    SERVER_SEND = %q"ss"

    SERVER_RECV = %q"sr"

end
