#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This script gets a normalized name for the architecture as used in Docker. This will be a subset
# of ones supported by buildx: https://github.com/docker/buildx/releases. This is a subset because
# for us to support a platform implies also supporting things like running NPM on it, so it should
# be an explicit act to add a platform.

set -ue

# Normalize docker_arch to what's available
#
# Note: s390x and ppc64le were added for Knative
docker_arch=${DOCKER_ARCH:-$(uname -m)}
case ${docker_arch} in
  amd64* )
    docker_arch=amd64
    ;;
  x86_64* )
    docker_arch=amd64
    ;;
  arm64* )
    docker_arch=arm64
    ;;
  aarch64* )
    docker_arch=arm64
    ;;
  s390x* )
    docker_arch=s390x
    ;;
  ppc64le* )
    docker_arch=ppc64le
    ;;
  * )
    >&2 echo "Unsupported DOCKER_ARCH: ${docker_arch}"
    exit 1;
esac

echo ${docker_arch}
