#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# Blocks until a named docker container with a valid HEALTHCHECK instruction is healthy or not:

set -ue

container_name=${1?container_name is required}
container_id=$(docker ps  -q -f name=${container_name})

while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "${container_id}")"; do
  case $status in
    starting) sleep 1;;
    healthy) exit 0;;
    unhealthy) exit 1;;
  esac
done
exit 1
