#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# Blocks until a named docker container with a valid HEALTHCHECK instruction is healthy or not:

set -ue

container_name=${1?container_name is required}
container_id=$(docker ps  -q -f name=${container_name})

while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "${container_id}")"; do
  case $status in
    starting) sleep 1;;
    healthy) exit 0;;
    unhealthy) exit 1;;
  esac
done
exit 1
