#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# HEALTHCHECK for use in `docker ps` or `docker-compose ps`.
# It can also be used as a readiness probe in k8s

# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
set -u +e

IP="$(hostname -i || echo '127.0.0.1')"

# cqlsh is eventually Python, which we don't want to install
NC_OUTPUT=$(nc -z ${IP} 9042 > /dev/null 2>&1)
NC_RC=$?
if [ "$NC_RC" == "0" ]; then
  exit 0
fi

echo Cassandra port check failed: $NC_OUTPUT
exit 1
