#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# ENTRYPOINT script that starts ZooKeeper and then Kafka
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

# Apply one-time deferred configuration that relies on ENV variables
#
# If the schema has been removed due to mounting, restore from our backup. see: install
if [ ! -d "data/data/zipkin2" ]; then
    cp -rf data-backup/* data/
fi

_ip_address() {
	# scrape the first non-localhost IP address of the container
	ip address | awk '
		$1 == "inet" && $NF != "lo" {
			gsub(/\/.+$/, "", $2)
			print $2
			exit
		}
	'
}

IP="$(_ip_address)"
sed -i "/listen_address: localhost/clisten_address: $IP" conf/cassandra.yaml
sed -i '/rpc_address: localhost/crpc_address: 0.0.0.0' conf/cassandra.yaml
sed -i "/# broadcast_address: 1.2.3.4/cbroadcast_address: $IP" conf/cassandra.yaml
sed -i "/# broadcast_rpc_address: 1.2.3.4/cbroadcast_rpc_address: $IP" conf/cassandra.yaml
sed -i "/          - seeds: \"127.0.0.1\"/c\          - seeds: $IP" conf/cassandra.yaml

exec bin/cassandra -f
