maven_layout()

jar_library(name='zipkin-cassandra',
  dependencies=[
    pants('oss/zipkin-cassandra/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-cassandra/src/test/scala')
  ]
)
