#!/bin/sh -ue

# This script sets up anything needed for `./deploy`. Do not assume `configure_test` was called.
#
# See [README.md] for an explanation of this and how CI should use it.
build-bin/docker/configure_docker_push
build-bin/gpg/configure_gpg

# When arch isn't amd64 zipkin-lens needs offline install
build-bin/maybe_install_npm
build-bin/maven_go_offline

# openzipkin/zipkin publishes Javadoc to https://zipkin.io/zipkin/ on release
build-bin/git/login_git
