#!/bin/sh -ue
#
# Copyright 2015-2023 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#


# Pushes docker as part of `deploy` or from a trigger tag
version=${1:-master}

# handle trigger pattern like /^docker-[0-9]+\.[0-9]+\.[0-9]+$/
case ${version} in
  docker-* )
    version=$(build-bin/git/version_from_trigger_tag docker- ${version})
    ;;
esac

build-bin/docker/docker_push openzipkin/zipkin ${version}
DOCKER_TARGET=zipkin-slim build-bin/docker/docker_push openzipkin/zipkin-slim ${version}

# testing images only push to ghcro.io
export DOCKER_RELEASE_REPOS=ghcr.io
# Don't attempt unfamiliar archs on test images
export DOCKER_ARCHS="amd64 arm64"

for name in $(ls docker/test-images/*/Dockerfile|cut -f3 -d/); do
  DOCKER_FILE=docker/test-images/${name}/Dockerfile build-bin/docker/docker_push openzipkin/${name} ${version}
done
