#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# uses 2.4 so we can use condition: service_healthy
version: "2.4"

# Test both authenticated and unauthenticated, as if there is a Spring problem,
# the latter will crash. We only need to use HEALTHCHECK for this.
services:
  eureka:
    image: openzipkin/zipkin-eureka:test
    container_name: eureka
  sut:
    image: openzipkin/zipkin-eureka:test
    container_name: sut
    environment:
      EUREKA_USERNAME: testuser
      EUREKA_PASSWORD: testpassword
    depends_on:
      eureka:
        condition: service_healthy
