#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script hydrates the Maven and NPM cache to make later processes operate with less chance of
# network problems.

# Prefetch all plugin and build dependencies in normal Maven projects
MAVEN_COMMAND="mvn -q --batch-mode -nsu --fail-never"
${MAVEN_COMMAND} -Prelease de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
# Prefetch dependencies used by zipkin-ui (NPM and NodeJS binary and dependencies of our build)
${MAVEN_COMMAND}  -pl zipkin-lens com.github.eirslett:frontend-maven-plugin:install-node-and-npm com.github.eirslett:frontend-maven-plugin:npm
# TODO: restructure integration tests so that they are also pre-fetched or add as dynamic dependency
