#!/bin/sh -ue

yamllint --format github .github/workflows/*.yml
# || true to work around https://github.com/tcort/markdown-link-check/issues/377
find . -name \*.md |grep -v node|xargs markdown-link-check -c ./build-bin/mlc_config.json || true
