#!/bin/sh -ue

build-bin/maven/maven_go_offline
export MAVEN_OPTS="$(build-bin/maven/maven_opts)"
# Prefetch dependencies used by zipkin-ui (NPM and NodeJS binary and dependencies of our build)
./mvnw -q --batch-mode -nsu -pl zipkin-lens generate-resources
