#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# ARM64 is not supported with musl, yet https://github.com/nodejs/node/blob/master/BUILDING.md
# Workaround this by installing node and npm directly. See issue #3166
set -uex

# Skip if we aren't Alpine
test -f /etc/alpine-release || exit 0

# Skip if we aren't arm64
ARCH=$(uname -m)
case ${ARCH} in
  arm64* )
    ;;
  aarch64* )
    ;;
  * )
    exit 0
esac

# Get the version of nodejs the build uses. Note: this will take time as it downloads Maven plugins
NODE_VERSION=$(mvn help:evaluate -Dexpression=node.version -q -DforceStdout -pl zipkin-lens)

# Repos for https://pkgs.alpinelinux.org/packages?name=nodejs-current are already in the base image
apk add --update --no-cache nodejs-current=~${NODE_VERSION} npm
