#!/bin/sh -ue
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This script hydrates the Maven and NPM cache to make later processes operate with less chance of
# network problems.
arch=$(uname -m)
case ${arch} in
  arm64* )
    arch=arm64
    ;;
  aarch64* )
    arch=arm64
    ;;
esac

# ARM64 is not supported with musl, yet https://github.com/nodejs/node/blob/master/BUILDING.md
# Workaround this by installing node and npm directly. See issue #3166
if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then

  export MAVEN_OPTS="$($(dirname "$0")/maven/maven_opts)"
  if [ -x ./mvnw ]; then alias mvn=${PWD}/mvnw; fi
  if [ "${MAVEN_PROJECT_BASEDIR:-.}" != "." ]; then cd ${MAVEN_PROJECT_BASEDIR}; fi

  # Get the version of nodejs the build uses. Note: this takes time as it downloads Maven plugins.
  node_version=$(mvn help:evaluate -Dexpression=node.version -DskipTests -q -DforceStdout -pl zipkin-lens)

  set -x
  # Repos for https://pkgs.alpinelinux.org/packages?name=nodejs are already in the base image.
  apk add --update --no-cache nodejs=~${node_version} npm
fi
