#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# Ensures Docker buildx is available and can build multi-architecture
#
# This should only happen when we are publishing multi-arch builds, as otherwise the setup will use
# Docker Hub pull quota and possibly cause a build outage.

# Verify we are on an arch that can publish multi-arch images
ARCH=$(uname -m)
if [ "$ARCH" != "x86_64" ]; then
  echo "multiarch/qemu-user-static doesn't support arch $ARCH"
  exit 1
fi

# Enable experimental features on the server (multi-arch)
echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
sudo service docker restart
# Enable experimental client features (eg docker buildx)
mkdir -p ${HOME}/.docker && echo '{"experimental":"enabled"}' > ${HOME}/.docker/config.json

# Add buildx plugin
BUILDX_VERSION=0.4.2
BUILDX_URL=https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-${TRAVIS_CPU_ARCH}
mkdir -p $HOME/.docker/cli-plugins
( cd $HOME/.docker/cli-plugins && wget -qO- $BUILDX_URL > docker-buildx && chmod 755 docker-buildx)
docker version

# Enable execution of different multi-architecture containers by QEMU and binfmt_misc
# See https://github.com/multiarch/qemu-user-static
docker run --rm --privileged ghcr.io/openzipkin/multiarch-qemu-user-static --reset -p yes
docker buildx create --name builder --use
