#!/bin/sh

set -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

echo "Running Maven tests and integration tests..."
./mvnw -nsu verify
export RELEASE_FROM_MAVEN_BUILD=true

echo "Building and testing openzipkin/zipkin..."
build-bin/docker/docker_build openzipkin/zipkin:test
build-bin/docker/docker_test_image openzipkin/zipkin

echo "Building and testing openzipkin/zipkin-slim..."
DOCKER_TARGET=zipkin-slim build-bin/docker/docker_build openzipkin/zipkin-slim:test
build-bin/docker/docker_test_image openzipkin/zipkin-slim

echo "Building and testing openzipkin/zipkin-ui..."
DOCKER_FILE=docker/test-images/zipkin-ui/Dockerfile build-bin/docker/docker_build openzipkin/zipkin-ui:test
build-bin/docker/docker_test_image openzipkin/zipkin-ui

