#!/usr/bin/env ruby

# Require Rails
require File.expand_path('../../config/environment',  __FILE__)
ZipkinUI::Application.initialize!

# Some common paths
LIB_PATH = Rails.root.join("lib")
GEN_PATH = LIB_PATH.join("gen-rb")

# password_file = "/Users/ENV['USER']}/.netrc"
#raise "Could not find .netrc file at #{password_file}" unless File.exists?(password_file)
# REGEX if we need to do basic auth at some point /.*password\s(.*)/i

# Thrift files to download
thrift_files = ["zipkin.thrift"]

thrift_files.each do |tf|
  out_file = LIB_PATH.join(tf)

  # Run the thrift command on the new files
  system("thrift --gen rb -o #{LIB_PATH} #{out_file}")

end

# Copy gen-rb up a directory
#system("cp -R #{GEN_PATH}/* #{LIB_PATH}")
FileUtils.cp_r Dir.glob("#{GEN_PATH}/*.rb"), LIB_PATH, :remove_destination => true

# Delete gen-rb
FileUtils.rm_rf(GEN_PATH)