maven_layout()

jar_library(
  name='zipkin-web',
  dependencies=[
    'zipkin/oss/zipkin-web/src/main/scala'
  ]
)

jar_library(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-web/src/test/scala'
  ]
)
