maven_layout()

jar_library(name='zipkin-web',
  dependencies=[
    pants('oss/zipkin-web/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-web/src/test/scala')
  ]
)
