#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to add a test
# activemq server, which is used as a span transport.

version: '2.4'

services:
  activemq:
    image: ghcr.io/openzipkin/zipkin-activemq:${TAG:-latest}
    container_name: activemq
    ports:  # expose the ActiveMQ port so apps can publish spans.
      - "61616:61616"

  zipkin:
    extends:
      file: docker-compose.yml
      service: zipkin
    # slim doesn't include Activemq support, so switch to the larger image
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    environment:
      - ACTIVEMQ_URL=failover:tcp://activemq:61616
    depends_on:
      activemq:
        condition: service_healthy
