#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to register
# zipkin into a test eureka server.

version: '2.4'

services:
  eureka:
    image: ghcr.io/openzipkin/zipkin-eureka:${TAG:-latest}
    container_name: eureka
# Uncomment to require authentication
#    environment:
#      - EUREKA_USERNAME=username
#      - EUREKA_PASSWORD=password
# Uncomment to expose the eureka port for testing
#    ports:
#      - 8761:8761

  zipkin:
    extends:
      file: docker-compose.yml
      service: zipkin
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
      # Uncomment to authenticate eureka
      #- EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
      - EUREKA_HOSTNAME=zipkin
    depends_on:
      eureka:
        condition: service_healthy

  # Generate traffic by hitting http://localhost:8081
  frontend:
    image: ghcr.io/openzipkin/brave-example:armeria
    container_name: frontend
    entrypoint: start-frontend
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
      # Uncomment to authenticate eureka
      #- EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
    ports:
      - 8081:8081
    depends_on:
      backend:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  # Serves the /api endpoint the frontend uses
  backend:
    image: ghcr.io/openzipkin/brave-example:armeria
    container_name: backend
    entrypoint: start-backend
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/v2
      # Uncomment to authenticate eureka
      #- EUREKA_SERVICE_URL=http://username:password@eureka:8761/eureka/v2
    depends_on:
      zipkin:
        condition: service_healthy
