maven_layout()

jar_library(
  name='zipkin-collector',
  dependencies=[
    'zipkin/oss/zipkin-collector/src/main/scala'
  ]
)

jar_library(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-collector/src/test/scala'
  ]
)
