maven_layout()

target(
  name='zipkin-collector',
  dependencies=[
    'zipkin/oss/zipkin-collector/src/main/scala'
  ]
)

target(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-collector/src/test/scala'
  ]
)
