maven_layout()

jar_library(name='zipkin-collector',
  dependencies=[
    pants('oss/zipkin-collector/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-collector/src/test/scala')
  ]
)
