#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# This script is only a convenience as the build environment is controlled in
# the Dockerfile. That said, it uses only basic shell commands to help it work
# on developer laptops as well as CI nodes. Mainly, this centralizes the base
# Java image mappings and ensures all metadata needed is taken from pom.xml.
set -ue

TARGET=${1:-zipkin}
TAG=${2:-test}
# When true, main images reuse zipkin-exec.jar and zipkin-slim.jar in the context root
RELEASE_FROM_CONTEXT=${RELEASE_FROM_CONTEXT:-false}
RELEASE_VERSION=${RELEASE_VERSION:-master}

# When publishing jars, we build with JDK 11 to ensure we can write 1.6 zipkin.jar for Brave.
# However, when creating Docker images, there's no such requirement.
# Hence, we use one version to keep the layer count manageable and centralized here.
JAVA_VERSION=${JAVA_VERSION:-15.0.1-15.28.13}

case ${TARGET} in
  zipkin )
    DOCKERFILE_PATH=docker/Dockerfile
    ;;
  zipkin-builder )
    DOCKERFILE_PATH=docker/builder/Dockerfile
    ;;
  zipkin-slim )
    DOCKERFILE_PATH=docker/Dockerfile
    ;;
  zipkin-ui )
    DOCKERFILE_PATH=docker/Dockerfile
    ;;
  zipkin-kafka )
    DOCKERFILE_PATH=docker/collector/kafka/Dockerfile
    ;;
  zipkin-cassandra )
    DOCKERFILE_PATH=docker/storage/cassandra/Dockerfile
    # Until Cassandra v4, we are stuck on JRE 8 for Cassandra
    JAVA_VERSION=8u272-8.50.0.21-jre-headless
    ;;
  zipkin-elasticsearch6 )
    DOCKERFILE_PATH=docker/storage/elasticsearch6/Dockerfile
    ;;
  zipkin-elasticsearch7 )
    DOCKERFILE_PATH=docker/storage/elasticsearch7/Dockerfile
    ;;
  zipkin-mysql )
    DOCKERFILE_PATH=docker/storage/mysql/Dockerfile
    ;;
  * )
    echo "Invalid TARGET: ${TARGET}"
    exit 1
esac

# Build the image
IMAGE=openzipkin/${TARGET}:${TAG}
echo "Building image ${IMAGE} with java_version ${JAVA_VERSION}"
docker build -f "${DOCKERFILE_PATH}" -t "${IMAGE}" \
    --build-arg java_version="${JAVA_VERSION}" \
    --build-arg release_from_context="${RELEASE_FROM_CONTEXT}" \
    --build-arg release_version="${RELEASE_VERSION}" \
    --target "${TARGET}" .
