#!/bin/bash

# This hook is called with the current directory set to the same as the Dockerfile, so we go back
# to top level.
cd ..

# We always build an image containing nginx and zipkin-lens in addition to the default image of zipkin-server
echo Building zipkin-ui
docker build -f $DOCKERFILE_PATH -t anuraaga/docker-hub-test-2:$DOCKER_TAG --target zipkin-ui --from-cache $IMAGE_NAME .

case "DOCKER_TAG" in
  master)
    # We rebuild the builder image on master push, not on release pushes.
    echo Building zipkin-builder
    docker build -f $DOCKERFILE_PATH -t anuraaga/docker-hub-test-3 --target zipkin-builder --from-cache $IMAGE_NAME .
  ;;

  *)
  ;;
esac
