#!/bin/bash

set -v

if [[ "$DOCKER_REPO" == "index.docker.io/openzipkin/zipkin" ]]; then
  # We always push zipkin-slim / zipkin-ui
  echo Pushing zipkin-slim and zipkin-ui
  IFS=',' read -ra TAGS <<< "$DOCKER_TAG"
  for tag in ${TAGS[@]}; do
    docker push "openzipkin/zipkin-slim:$tag"
    docker push "openzipkin/zipkin-ui:$tag"

    # We also push storage images on every build
    for storage in cassandra; do
      docker push "openzipkin/zipkin-${storage}:$tag"
    done
  done

  if [[ "$DOCKER_TAG" == "master" ]]; then
    # We repush the builder image on master push, not on release pushes.
    echo Pushing zipkin-builder
    # zipkin-builder is just a cache of maven / npm dependencies, there's no need to version it
    # with docker tags.
    docker push openzipkin/zipkin-builder
  fi
fi
