#!/bin/bash

if [[ "$DOCKER_REPO" == "openzipkin/zipkin" ]]; then
  # We always push an image containing nginx and zipkin-lens in addition to the default image of zipkin-server
  echo Pushing zipkin-ui
  docker push openzipkin/zipkin-ui:$DOCKER_TAG

  if [[ "$DOCKER_TAG" == "master" ]]; then
    # We repush the builder image on master push, not on release pushes.
    echo Pushing zipkin-builder
    # zipkin-builder is just a cache of maven / npm dependencies, there's no need to version it
    # with docker tags.
    docker push openzipkin/zipkin-builder
  fi
fi
