#!/bin/bash
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# This script relies on variables defined by Docker Hub Autobuild
# https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing
#
# This script uses /bin/bash, not /bin/sh, because /bin/sh on Docker Hub image uses doesn't allow
# substitutions like: ${DOCKER_TAG//,/ }
set -eux

if [ "${DOCKER_TAG}" = "master" ]; then
  echo Travis builds master, not Docker Hub
  exit 1
fi

# This hook is called with the current directory set to the same as the Dockerfile, so we go back
# to top-level.
cd ..

if [ "${DOCKER_REPO}" = "index.docker.io/openzipkin/zipkin" ]; then
  for tag in ${DOCKER_TAG//,/ }; do
    for target in $(docker/bin/targets-to-build); do
      image="openzipkin/${target}:${tag}"
      echo Pushing ${image}
      docker push ${image}
    done
  done
fi
