maven_layout()

jar_library(
  name='zipkin-scrooge',
  dependencies=[
    'zipkin/oss/zipkin-scrooge/src/main/scala',
  ]
)

jar_library(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-scrooge/src/test/scala'
  ]
)
