maven_layout()

jar_library(name='zipkin-collector-core',
  dependencies=[
    pants('oss/zipkin-collector-core/src/main/scala'),
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-collector-core/src/test/scala')
  ]
)
