maven_layout()


jar_library(name='zipkin-collector-scribe',
  dependencies=[
    pants('oss/zipkin-collector-scribe/src/main/scala'),
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-collector-scribe/src/test/scala')
  ]
)

