maven_layout()

target(name='zipkin-common',
  dependencies=[
    'zipkin/oss/zipkin-common/src/main/scala'
  ]
)

target(name='tests',
  dependencies=[
    'zipkin/oss/zipkin-common/src/test/scala'
  ]
)
