maven_layout()

jar_library(name='zipkin-common',
  dependencies=[
    'zipkin/oss/zipkin-common/src/main/scala'
  ]
)

jar_library(name='tests',
  dependencies=[
    'zipkin/oss/zipkin-common/src/test/scala'
  ]
)
