maven_layout()

jar_library(name='zipkin-common',
  dependencies=[
    pants('oss/zipkin-common/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-common/src/test/scala')
  ]
)
