#!/bin/bash

echo "Executing pre_build hook"

case "$DOCKER_REPO" in
  openzipkin/zipkin-builder)
    # Remove after Docker Hub updates to Docker 19.03 to include
    # https://github.com/moby/moby/issues/12886#issuecomment-480575928
    echo "Copying zipkin-builder dockerignore"
    cp docker/builder/Dockerfile.dockerignore .dockerignore
  ;;

  *)
  ;;
esac
