maven_layout()

jar_library(name='zipkin-storm',
  dependencies=[
    pants('oss/zipkin-storm/src/main/scala'),
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-storm/src/test/scala')
  ]
)
