export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_SPANS_REQUEST = 'FETCH_SPANS_REQUEST';
export const FETCH_SPANS_SUCCESS = 'FETCH_SPANS_SUCCESS';
export const FETCH_SPANS_FAILURE = 'FETCH_SPANS_FAILURE';
export const CLEAR_SPANS = 'CLEAR_SPANS';

export const FETCH_TRACE_REQUEST = 'FETCH_TRACE_REQUEST';
export const FETCH_TRACE_SUCCESS = 'FETCH_TRACE_SUCCESS';
export const FETCH_TRACE_FAILURE = 'FETCH_TRACE_FAILURE';

export const FETCH_TRACES_REQUEST = 'FETCH_TRACES_REQUEST';
export const FETCH_TRACES_SUCCESS = 'FETCH_TRACES_SUCCESS';
export const FETCH_TRACES_FAILURE = 'FETCH_TRACES_FAILURE';
export const CLEAR_TRACES = 'CLEAR_TRACES';

export const FETCH_DEPENDENCIES_REQUEST = 'FETCH_DEPENDENCIES_REQUEST';
export const FETCH_DEPENDENCIES_SUCCESS = 'FETCH_DEPENDENCIES_SUCCESS';
export const FETCH_DEPENDENCIES_FAILURE = 'FETCH_DEPENDENCIES_FAILURE';
export const CLEAR_DEPENDENCIES = 'CLEAR_DEPENDENCIES';

export const FETCH_AUTOCOMPLETE_KEYS_REQUEST = 'FETCH_AUTOCOMPLETE_KEYS_REQUEST';
export const FETCH_AUTOCOMPLETE_KEYS_SUCCESS = 'FETCH_AUTOCOMPLETE_KEYS_SUCCESS';
export const FETCH_AUTOCOMPLETE_KEYS_FAILURE = 'FETCH_AUTOCOMPLETE_KEYS_FAILURE';

export const FETCH_AUTOCOMPLETE_VALUES_REQUEST = 'FETCH_AUTOCOMPLETE_VALUES_REQUEST';
export const FETCH_AUTOCOMPLETE_VALUES_SUCCESS = 'FETCH_AUTOCOMPLETE_VALUES_SUCCESS';
export const FETCH_AUTOCOMPLETE_VALUES_FAILURE = 'FETCH_AUTOCOMPLETE_VALUES_FAILURE';

export const GLOBAL_SEARCH_SET_LOOKBACK_CONDITION = 'GLOBAL_SEARCH_SET_LOOKBACK_CONDITION';
export const GLOBAL_SEARCH_SET_LIMIT_CONDITION = 'GLOBAL_SEARCH_SET_LIMIT_CONDITION';
export const GLOBAL_SEARCH_ADD_CONDITION = 'GLOBAL_SEARCH_ADD_CONDITION';
export const GLOBAL_SEARCH_DELETE_CONDITION = 'GLOBAL_SEARCH_DELETE_CONDITION';
export const GLOBAL_SEARCH_CHANGE_CONDITION_KEY = 'GLOBAL_SEARCH_CHANGE_CONDITION_KEY';
export const GLOBAL_SEARCH_CHANGE_CONDITION_VALUE = 'GLOBAL_SEARCH_CHANGE_CONDITION_VALUE';

export const TRACE_VIEWER__LOAD_TRACE = 'TRACE_VIEWER__LOAD_TRACE';
