export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';

export const FETCH_SPANS_REQUEST = 'FETCH_SPANS_REQUEST';
export const FETCH_SPANS_SUCCESS = 'FETCH_SPANS_SUCCESS';
export const FETCH_SPANS_FAILURE = 'FETCH_SPANS_FAILURE';
export const CLEAR_SPANS = 'CLEAR_SPANS';

export const FETCH_TRACE_REQUEST = 'FETCH_TRACE_REQUEST';
export const FETCH_TRACE_SUCCESS = 'FETCH_TRACE_SUCCESS';
export const FETCH_TRACE_FAILURE = 'FETCH_TRACE_FAILURE';

export const FETCH_TRACES_REQUEST = 'FETCH_TRACES_REQUEST';
export const FETCH_TRACES_SUCCESS = 'FETCH_TRACES_SUCCESS';
export const FETCH_TRACES_FAILURE = 'FETCH_TRACES_FAILURE';
export const CLEAR_TRACES = 'CLEAR_TRACES';

export const FETCH_DEPENDENCIES_REQUEST = 'FETCH_DEPENDENCIES_REQUEST';
export const FETCH_DEPENDENCIES_SUCCESS = 'FETCH_DEPENDENCIES_SUCCESS';
export const FETCH_DEPENDENCIES_FAILURE = 'FETCH_DEPENDENCIES_FAILURE';
export const CLEAR_DEPENDENCIES = 'CLEAR_DEPENDENCIES';
