#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

sed "s~proxy_pass http://localhost:9411~proxy_pass ${ZIPKIN_BASE_URL}~g" \
 /etc/nginx/conf.d/zipkin.conf.template > /etc/nginx/nginx.conf

exec nginx "$@"
