#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

set -ue

# Allocate commits to CI, not the owner of the deploy key
git config user.name "zipkinci"
git config user.email "zipkinci+zipkin-dev@googlegroups.com"

# Setup https authentication credentials, used by ./mvnw release:prepare
git config credential.helper "store --file=.git/credentials"
echo "https://$GH_TOKEN:@github.com" > .git/credentials
