maven_layout()

jar_library(
  name='zipkin-query',
  dependencies=[
    'zipkin/oss/zipkin-query/src/main/scala'
  ]
)

jar_library(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-query/src/test/scala'
  ]
)
