maven_layout()

target(
  name='zipkin-query',
  dependencies=[
    'zipkin/oss/zipkin-query/src/main/scala'
  ]
)

target(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-query/src/test/scala'
  ]
)
