maven_layout()

jar_library(name='zipkin-query',
  dependencies=[
    pants('oss/zipkin-query/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-query/src/test/scala')
  ]
)
