#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# This script checks each variable value, so it isn't important to fail on unbound (set -u)
set -e

maven_project_basedir=${MAVEN_PROJECT_BASEDIR:-.}
pom="${maven_project_basedir}/pom.xml"

# fail if there's no pom
test -f "${pom}"

arch=$(uname -m)
case ${arch} in
  arm64* )
    arch=arm64
    ;;
  aarch64* )
    arch=arm64
    ;;
esac

maven_opts="${MAVEN_OPTS:-}"
if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then
  # Defensively avoid arm64+alpine problems with posix_spawn
  maven_opts="${maven_opts} -Djdk.lang.Process.launchMechanism=vfork"
fi

echo ${maven_opts}
