#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script creates a git `MAJOR.MINOR.PATCH` version tag which later will have `deploy` run against it.
#
# In CI..
#  * trigger pattern: tag =~ /^release-[0-9]+\.[0-9]+\.[0-9]+/
#  * build-bin/git/login_git must be called before invoking this.

export MAVEN_OPTS="$($(dirname "$0")/maven_opts)"

trigger_tag=${1?trigger_tag is required. Ex release-1.2.3}
release_version=$(build-bin/git/version_from_trigger_tag release- ${trigger_tag})

# Checkout the branch that triggered this build
git fetch --tags origin
commit_sha=$(git rev-parse "$trigger_tag")
branches=$(git branch --contains "$commit_sha")
branch_name=$(echo "$branches" | head -n 1 | awk '{print $2}')
if [ -z "$branch_name" ]; then
  default_branch="master"
  echo "Unable to determine a valid branch. Auto-selecting the default branch: $default_branch"
  branch_name=$default_branch
fi
echo "Ready to checkout branch $branch_name"
git checkout "$branch_name"

git submodule update --init --recursive
# Prepare and push release commits and the version tag (N.N.N), which triggers deployment.
./mvnw --batch-mode -nsu -DreleaseVersion=${release_version} -Denforcer.fail=false -Darguments="-DskipTests -Dcheckstyle.skip=true -Denforcer.fail=false" release:prepare
