#!/bin/sh
#
# Copyright 2015-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# This script checks each variable value, so it isn't important to fail on unbound (set -u)
set -e

maven_project_basedir=${MAVEN_PROJECT_BASEDIR:-.}
pom="${maven_project_basedir}/pom.xml"

# fail if there's no pom
test -f "${pom}"

arch=$(uname -m)
case ${arch} in
  arm64* )
    arch=arm64
    ;;
  aarch64* )
    arch=arm64
    ;;
esac

maven_opts="${MAVEN_OPTS:-}"
if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then
  # Defensively avoid arm64+alpine problems with posix_spawn
  maven_opts="${maven_opts} -Djdk.lang.Process.launchMechanism=vfork"
fi

echo ${maven_opts}
