#!/bin/sh
#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# ENTRYPOINT script that starts ActiveMQ
#
# This intentionally locates config using the current working directory, in order to consolidate
# Dockerfile instructions to WORKDIR
set -eu

# Configure the Docker HEALTHCHECK
# Configure the Docker HEALTHCHECK
export HEALTHCHECK_PORT=61616
export HEALTHCHECK_KIND=tcp

echo Starting ActiveMQ
exec bin/activemq console

