maven_layout()

jar_library(name='zipkin-receiver-scribe',
  dependencies=[
    pants('oss/zipkin-receiver-scribe/src/main/scala')
  ]
)

jar_library(name='tests',
  dependencies=[
    pants('oss/zipkin-receiver-scribe/src/test/scala')
  ]
)
