maven_layout()

jar_library(
  name='zipkin-receiver-scribe',
  dependencies=[
    'zipkin/oss/zipkin-receiver-scribe/src/main/scala'
  ]
)

jar_library(
  name='tests',
  dependencies=[
    'zipkin/oss/zipkin-receiver-scribe/src/test/scala'
  ]
)
